[package]
name = "rust_demo_s25"
version = "0.1.0"
edition = "2021"

[dependencies]
rustls = "0.23.22"
webpki-roots = "0.26.8"
anyhow = "1"
rand = "0.9"
crossbeam = "0.8"
nix = {version = "0.29.0", features = ["process", "fs"]}